// examples/vue-token/src/App.vue
<template>
  <div class="container">
    <header>
      <h1>🪙 FHEVM Encrypted Token</h1>
      <p class="subtitle">Vue 3 + FHEVM SDK Example</p>
      <p v-if="fhevm.network.value" class="network">
        Network: {{ fhevm.network.value.name }}
      </p>
    </header>

    <div v-if="!fhevm.isInitialized.value" class="loading">
      Initializing FHEVM...
    </div>

    <template v-else>
      <div v-if="!wallet.address.value" class="wallet-section">
        <button 
          @click="wallet.connect((window as any).ethereum)" 
          :disabled="wallet.isConnecting.value"
          class="btn btn-primary"
        >
          {{ wallet.isConnecting.value ? 'Connecting...' : 'Connect Wallet' }}
        </button>
      </div>

      <div v-else class="main-content">
        <div class="wallet-info">
          <p><strong>Connected:</strong> {{ shortAddress(wallet.address.value!) }}</p>
          <button @click="wallet.disconnect" class="btn btn-secondary">
            Disconnect
          </button>
        </div>

        <div class="card">
          <h2>💰 Private Balance</h2>
          <p class="balance">{{ balance || '***' }} TOKENS</p>
          <div class="button-group">
            <button 
              @click="handleViewBalance" 
              :disabled="isViewing || encrypt.isEncrypting.value"
              class="btn"
            >
              {{ isViewing ? 'Encrypting...' : '🔒 Encrypt Balance' }}
            </button>
            <button 
              v-if="lastEncryptedHandle"
              @click="handleRevealBalance" 
              :disabled="decrypt.isDecrypting.value"
              class="btn btn-reveal"
            >
              {{ decrypt.isDecrypting.value ? 'Decrypting...' : '🔓 Reveal Balance' }}
            </button>
          </div>
          <div v-if="decryptedBalance !== null" class="decrypted-info">
            ✅ Decrypted: <strong>{{ decryptedBalance.toString() }} TOKENS</strong>
          </div>
        </div>

        <div class="card">
          <h2>📤 Transfer Tokens</h2>
          <div class="form-group">
            <label>Recipient Address:</label>
            <input 
              v-model="recipient" 
              type="text"
              placeholder="0x..."
              class="input"
            />
          </div>
          <div class="form-group">
            <label>Amount:</label>
            <input 
              v-model.number="amount" 
              type="number"
              placeholder="0"
              class="input"
            />
          </div>
          <button 
            @click="handleTransfer" 
            :disabled="isTransferring"
            class="btn btn-primary"
          >
            {{ isTransferring ? 'Transferring...' : 'Transfer' }}
          </button>
        </div>

        <div v-if="txHash" class="success">
          ✅ Transaction: {{ shortAddress(txHash) }}
        </div>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useFHEVM, useWallet, useEncrypt, useDecrypt } from '@mixaspro/vue'

const fhevm = useFHEVM({
  chainId: 11155111,
  rpcUrl: 'https://ethereum-sepolia-rpc.publicnode.com'
})

const wallet = useWallet()
const encrypt = useEncrypt()
const decrypt = useDecrypt()

const balance = ref<string | null>(null)
const recipient = ref('')
const amount = ref(0)
const txHash = ref('')
const isViewing = ref(false)
const isTransferring = ref(false)
const lastEncryptedHandle = ref<string | null>(null)
const decryptedBalance = ref<bigint | null>(null)

const TOKEN_ABI = [
  {
    inputs: [],
    name: 'balanceOf',
    outputs: [{ name: '', type: 'euint64' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'encryptedAmount', type: 'bytes' }
    ],
    name: 'transfer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
]

const CONTRACT_ADDRESS = '0x5FbDB2315678afecb367f032d93F642f64180aa3'

async function handleViewBalance() {
  isViewing.value = true
  try {
    // Encrypt a mock balance to demonstrate encryption
    const mockBalance = 1000
    const encrypted = await encrypt.encrypt(mockBalance, 'euint64')
    
    // Store handle for decryption
    if (encrypted && encrypted.handle) {
      lastEncryptedHandle.value = encrypted.handle
      balance.value = '***'
      alert('Balance encrypted! Click "Reveal Balance" to decrypt.')
    }
  } catch (error) {
    console.error('Failed to encrypt balance:', error)
    alert('Failed to encrypt balance')
  } finally {
    isViewing.value = false
  }
}

async function handleRevealBalance() {
  if (!lastEncryptedHandle.value) {
    alert('No encrypted balance. Click "View Balance" first.')
    return
  }

  try {
    const result = await decrypt.decrypt(lastEncryptedHandle.value)
    decryptedBalance.value = result as bigint
    balance.value = decryptedBalance.value.toString()
  } catch (error) {
    console.error('Failed to decrypt balance:', error)
    alert(`Decryption failed: ${error instanceof Error ? error.message : 'Unknown error'}`)
  }
}

async function handleTransfer() {
  if (!recipient.value || !amount.value) {
    alert('Please fill all fields')
    return
  }

  isTransferring.value = true
  try {
    const encrypted = await encrypt.encrypt(amount.value, 'euint64')
    
    // In real app, would call contract
    txHash.value = '0x1234...5678'
    alert('Transfer successful!')
    
    recipient.value = ''
    amount.value = 0
  } catch (error) {
    console.error('Transfer failed:', error)
    alert('Transfer failed')
  } finally {
    isTransferring.value = false
  }
}

function shortAddress(addr: string): string {
  return `${addr.slice(0, 6)}...${addr.slice(-4)}`
}
</script>

<style scoped>
.balance {
  font-size: 2rem;
  font-weight: bold;
  color: #10b981;
  margin: 1rem 0;
}

.button-group {
  display: flex;
  gap: 0.75rem;
  margin-top: 1rem;
}

.button-group .btn {
  flex: 1;
}

.btn-reveal {
  background: linear-gradient(135deg, #38b2ac 0%, #319795 100%);
}

.btn-reveal:hover:not(:disabled) {
  background: linear-gradient(135deg, #319795 0%, #2c7a7b 100%);
}

.decrypted-info {
  margin-top: 1rem;
  padding: 0.75rem;
  background: #d4edda;
  border: 1px solid #c3e6cb;
  border-radius: 8px;
  color: #155724;
  text-align: center;
}

.decrypted-info strong {
  font-size: 1.1rem;
}
</style>

// examples/svelte-voting/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { 
    initializeFHEVM, 
    isInitialized, 
    connectWallet, 
    wallet,
    encrypt,
    isEncrypting,
    encryptedData,
    writeContract,
    isWriting,
    transactionReceipt,
    decrypt,
    isDecrypting,
    decryptedData,
    decryptionError
  } from '@mixaspro/svelte'

  const VOTING_ABI = [
    {
      inputs: [{ name: 'encryptedVote', type: 'bytes' }],
      name: 'vote',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'getTotalVotes',
      outputs: [{ name: '', type: 'euint32' }],
      stateMutability: 'view',
      type: 'function',
    },
  ]

  const CONTRACT_ADDRESS = '0x5FbDB2315678afecb367f032d93F642f64180aa3'

  let selectedOption = 0
  let lastEncryptedHandle: string | null = null
  let decryptedVoteValue: bigint | null = null

  onMount(async () => {
    await initializeFHEVM({ 
      chainId: 11155111,
      rpcUrl: 'https://ethereum-sepolia-rpc.publicnode.com'
    })
  })

  async function handleConnect() {
    try {
      await connectWallet((window as any).ethereum)
    } catch (error) {
      console.error('Failed to connect:', error)
      alert('Failed to connect wallet')
    }
  }

  async function handleVote() {
    try {
      // Encrypt vote (0, 1, or 2 for option A, B, or C)
      const encrypted = await encrypt(selectedOption, 'euint32')
      
      // Store handle for decryption demo
      if (encrypted && encrypted.handle) {
        lastEncryptedHandle = encrypted.handle
      }
      
      // Submit vote
      await writeContract({
        address: CONTRACT_ADDRESS,
        abi: VOTING_ABI,
        functionName: 'vote',
        args: [encrypted.value],
      })
      
      alert('Vote submitted successfully!')
    } catch (error) {
      console.error('Failed to vote:', error)
      alert(`Error: ${error instanceof Error ? error.message : 'Unknown error'}`)`)
    }
  }

  async function handleDecryptVote() {
    if (!lastEncryptedHandle) {
      alert('No encrypted vote to decrypt. Please vote first.')
      return
    }

    try {
      const result = await decrypt(lastEncryptedHandle)
      decryptedVoteValue = result as bigint
    } catch (error) {
      console.error('Failed to decrypt vote:', error)
      alert(`Decryption Error: ${error instanceof Error ? error.message : 'Unknown error'}`)
    }
  }
</script>

<div class="container">
  <header>
    <h1>🗳️ FHEVM Private Voting</h1>
    <p class="subtitle">Svelte + FHEVM SDK Example</p>
  </header>

  {#if !$isInitialized}
    <div class="loading">Initializing FHEVM...</div>
  {:else if !$wallet}
    <div class="wallet-section">
      <button on:click={handleConnect} class="btn btn-primary">
        Connect Wallet
      </button>
    </div>
  {:else}
    <div class="wallet-info">
      <p>Connected: <code>{$wallet.address.slice(0, 6)}...{$wallet.address.slice(-4)}</code></p>
    </div>

    <div class="voting-section">
      <h2>Cast Your Vote</h2>
      <p class="info">Your vote is encrypted and remains private</p>

      <div class="options">
        <label class="option">
          <input 
            type="radio" 
            bind:group={selectedOption} 
            value={0}
            disabled={$isEncrypting || $isWriting}
          />
          <span>Option A</span>
        </label>

        <label class="option">
          <input 
            type="radio" 
            bind:group={selectedOption} 
            value={1}
            disabled={$isEncrypting || $isWriting}
          />
          <span>Option B</span>
        </label>

        <label class="option">
          <input 
            type="radio" 
            bind:group={selectedOption} 
            value={2}
            disabled={$isEncrypting || $isWriting}
          />
          <span>Option C</span>
        </label>
      </div>

      <button
        on:click={handleVote}
        disabled={$isEncrypting || $isWriting}
        class="btn btn-primary btn-vote"
      >
        {$isEncrypting ? 'Encrypting...' : $isWriting ? 'Submitting...' : 'Submit Vote'}
      </button>

      {#if $transactionReceipt}
        <div class="success">
          ✅ Vote submitted successfully!
          <br />
          <code>{$transactionReceipt.hash.slice(0, 10)}...</code>
        </div>
      {/if}
    </div>

    {#if lastEncryptedHandle}
      <div class="decrypt-section">
        <h2>Step 2: Decrypt Your Vote</h2>
        <p class="info">Decrypt to verify your encrypted vote value</p>

        <button
          on:click={handleDecryptVote}
          disabled={$isDecrypting}
          class="btn btn-secondary"
        >
          {$isDecrypting ? 'Decrypting...' : '🔓 Decrypt Vote'}
        </button>

        {#if $decryptionError}
          <div class="error">
            ❌ Decryption failed: {$decryptionError.message}
          </div>
        {/if}

        {#if decryptedVoteValue !== null}
          <div class="decrypted-result">
            <h3>Decrypted Vote Value:</h3>
            <p class="vote-value">{decryptedVoteValue.toString()}</p>
            <p class="vote-label">
              (Option {['A', 'B', 'C'][Number(decryptedVoteValue)] || 'Unknown'})
            </p>
          </div>
        {/if}
      </div>
    {/if}

    <div class="info-section">
      <h3>How Private Voting Works:</h3>
      <ol>
        <li>Select your preferred option</li>
        <li>Vote is encrypted locally using FHE</li>
        <li>Encrypted vote is submitted to blockchain</li>
        <li>Decrypt to verify your vote (demo only)</li>
        <li>In production: votes remain private until reveal phase</li>
      </ol>
    </div>
  {/if}
</div>

<style>
  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }

  :global(body) {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .container {
    max-width: 600px;
    width: 90%;
    background: white;
    border-radius: 16px;
    padding: 2rem;
    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
  }

  header {
    text-align: center;
    margin-bottom: 2rem;
  }

  h1 {
    font-size: 2rem;
    color: #333;
    margin-bottom: 0.5rem;
  }

  .subtitle {
    color: #666;
    font-size: 1rem;
  }

  .loading {
    text-align: center;
    padding: 2rem;
    color: #666;
  }

  .wallet-section {
    text-align: center;
    padding: 2rem 0;
  }

  .wallet-info {
    padding: 1rem;
    background: #f8f9fa;
    border-radius: 8px;
    margin-bottom: 1.5rem;
    text-align: center;
  }

  .wallet-info code {
    background: #e9ecef;
    padding: 0.25rem 0.5rem;
    border-radius: 4px;
    font-family: 'Courier New', monospace;
  }

  .voting-section {
    margin-top: 1.5rem;
    padding: 1.5rem;
    border: 2px solid #e9ecef;
    border-radius: 8px;
  }

  h2 {
    font-size: 1.5rem;
    margin-bottom: 0.5rem;
    color: #333;
  }

  .info {
    color: #666;
    font-size: 0.9rem;
    margin-bottom: 1.5rem;
  }

  .options {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    margin-bottom: 1.5rem;
  }

  .option {
    display: flex;
    align-items: center;
    padding: 1rem;
    border: 2px solid #e9ecef;
    border-radius: 8px;
    cursor: pointer;
    transition: all 0.2s;
  }

  .option:hover {
    border-color: #667eea;
    background: #f8f9ff;
  }

  .option input {
    margin-right: 1rem;
  }

  .option span {
    font-size: 1.1rem;
    color: #333;
  }

  .btn {
    padding: 0.75rem 1.5rem;
    border: none;
    border-radius: 8px;
    font-size: 1rem;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s;
  }

  .btn:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .btn-primary {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    width: 100%;
  }

  .btn-primary:hover:not(:disabled) {
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(102, 126, 234, 0.4);
  }

  .btn-vote {
    margin-top: 1rem;
  }

  .success {
    margin-top: 1rem;
    padding: 1rem;
    background: #d4edda;
    border: 1px solid #c3e6cb;
    border-radius: 8px;
    color: #155724;
  }

  .success code {
    background: #c3e6cb;
    padding: 0.25rem 0.5rem;
    border-radius: 4px;
    font-family: 'Courier New', monospace;
  }

  .decrypt-section {
    margin-top: 1.5rem;
    padding: 1.5rem;
    border: 2px solid #e9ecef;
    border-radius: 8px;
    background: #f8f9ff;
  }

  .btn-secondary {
    background: linear-gradient(135deg, #38b2ac 0%, #319795 100%);
    color: white;
    width: 100%;
    margin-top: 1rem;
  }

  .btn-secondary:hover:not(:disabled) {
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(56, 178, 172, 0.4);
  }

  .error {
    margin-top: 1rem;
    padding: 1rem;
    background: #f8d7da;
    border: 1px solid #f5c6cb;
    border-radius: 8px;
    color: #721c24;
  }

  .decrypted-result {
    margin-top: 1.5rem;
    padding: 1.5rem;
    background: #d4edda;
    border: 2px solid #c3e6cb;
    border-radius: 8px;
    text-align: center;
  }

  .decrypted-result h3 {
    font-size: 1.1rem;
    margin-bottom: 0.75rem;
    color: #155724;
  }

  .vote-value {
    font-size: 2.5rem;
    font-weight: bold;
    color: #155724;
    margin: 0.5rem 0;
  }

  .vote-label {
    font-size: 1.2rem;
    color: #155724;
    margin-top: 0.5rem;
  }

  .info-section {
    margin-top: 2rem;
    padding: 1rem;
    background: #f8f9fa;
    border-radius: 8px;
  }

  h3 {
    font-size: 1.2rem;
    margin-bottom: 0.75rem;
    color: #333;
  }

  ol {
    margin-left: 1.5rem;
    color: #666;
    line-height: 1.8;
  }
</style>
