// examples/angular-auction/src/app/app.component.ts
import { Component, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { FormsModule } from '@angular/forms'
import { FHEVMClient } from '@mixaspro/core'

interface Bid {
  id: number
  timestamp: Date
  amount: string
  encryptedHandle?: string
  decryptedAmount?: bigint
  status: 'pending' | 'confirmed'
  isDecrypting?: boolean
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  private fhevm: FHEVMClient | null = null
  
  isInitialized = false
  walletAddress: string | null = null
  isConnecting = false
  
  bidAmount = 0
  isBidding = false
  bids: Bid[] = []
  
  auctionItem = {
    name: '🎨 Digital Artwork',
    description: 'Rare NFT by Famous Artist',
    currentBid: '???',
    timeLeft: '2h 30m'
  }

  async ngOnInit() {
    try {
      this.fhevm = new FHEVMClient()
      await this.fhevm.initialize({
        chainId: 11155111,
        rpcUrl: 'https://eth-sepolia.g.alchemy.com/v2/tdHjNLQj6qDZOj8XlibqQEVxvKh_5Tqw',
        wasmPath: '/angular-auction/assets/wasm/'
      })
      this.isInitialized = true
    } catch (err) {
      console.error('Failed to initialize:', err)
      alert('Failed to initialize FHEVM')
    }
  }

  async connectWallet() {
    if (!(window as any).ethereum) {
      alert('Please install MetaMask')
      return
    }

    if (!this.fhevm) {
      alert('FHEVM not initialized')
      return
    }

    this.isConnecting = true
    try {
      const wallet = await this.fhevm.connectWallet((window as any).ethereum)
      this.walletAddress = wallet.address
    } catch (err) {
      console.error('Connection failed:', err)
      alert('Failed to connect wallet')
    } finally {
      this.isConnecting = false
    }
  }

  disconnectWallet() {
    this.walletAddress = null
  }

  async placeBid() {
    if (!this.bidAmount || this.bidAmount <= 0) {
      alert('Please enter a valid bid amount')
      return
    }

    if (!this.fhevm) {
      alert('FHEVM not initialized')
      return
    }

    this.isBidding = true
    
    try {
      const encrypted = await this.fhevm.encrypt(this.bidAmount, 'euint64')
      
      if (!encrypted) {
        throw new Error('Encryption failed')
      }

      const newBid: Bid = {
        id: this.bids.length + 1,
        timestamp: new Date(),
        amount: '***',
        encryptedHandle: encrypted.handle,
        status: 'pending',
        isDecrypting: false
      }
      
      this.bids.unshift(newBid)
      
      setTimeout(() => {
        newBid.status = 'confirmed'
      }, 2000)

      alert('Bid placed successfully!')
      this.bidAmount = 0
    } catch (error) {
      console.error('Bid failed:', error)
      alert('Failed to place bid')
    } finally {
      this.isBidding = false
    }
  }

  async revealBid(bid: Bid) {
    if (!bid.encryptedHandle) {
      alert('No encrypted bid to reveal')
      return
    }

    if (!this.fhevm) {
      alert('FHEVM not initialized')
      return
    }

    bid.isDecrypting = true
    
    try {
      const instance = this.fhevm.getInstance()
      if (!instance) {
        throw new Error('FHEVM instance not available')
      }

      const results = await instance.publicDecrypt([bid.encryptedHandle])
      const firstKey = Object.keys(results)[0]
      
      if (!firstKey) {
        throw new Error('No decryption result')
      }

      const decrypted = results[firstKey] as bigint
      bid.decryptedAmount = decrypted
      bid.amount = decrypted.toString()
    } catch (err: any) {
      console.error('Decryption failed:', err)
      alert(`Failed to decrypt: ${err.message}`)
    } finally {
      bid.isDecrypting = false
    }
  }

  shortAddress(address: string): string {
    return `${address.slice(0, 6)}...${address.slice(-4)}`
  }

  getTimeSince(date: Date): string {
    const seconds = Math.floor((new Date().getTime() - date.getTime()) / 1000)
    
    if (seconds < 60) return `${seconds}s ago`
    if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`
    return `${Math.floor(seconds / 3600)}h ago`
  }
}

<div class="container">
  <header>
    <h1>🔨 Blind Auction</h1>
    <p class="subtitle">Angular + FHEVM SDK</p>
  </header>

  <div *ngIf="!isInitialized" class="loading">
    Initializing FHEVM...
  </div>

  <ng-container *ngIf="isInitialized">
    <div *ngIf="!walletAddress" class="wallet-section">
      <button 
        (click)="connectWallet()" 
        [disabled]="isConnecting"
        class="btn btn-primary"
      >
        {{ isConnecting ? 'Connecting...' : 'Connect Wallet' }}
      </button>
    </div>

    <div *ngIf="walletAddress" class="main-content">
      <div class="wallet-info">
        <p><strong>Connected:</strong> {{ shortAddress(walletAddress) }}</p>
        <button (click)="disconnectWallet()" class="btn btn-secondary">
          Disconnect
        </button>
      </div>

      <div class="auction-card">
        <h2>{{ auctionItem.name }}</h2>
        <p class="description">{{ auctionItem.description }}</p>
        
        <div class="auction-stats">
          <div class="stat">
            <span class="label">Current Highest Bid:</span>
            <span class="value">{{ auctionItem.currentBid }}</span>
          </div>
          <div class="stat">
            <span class="label">Time Left:</span>
            <span class="value time">{{ auctionItem.timeLeft }}</span>
          </div>
        </div>

        <div class="bid-section">
          <h3>💰 Place Your Bid</h3>
          <p class="bid-note">
            Your bid is completely private. Other bidders cannot see your amount.
          </p>
          
          <div class="bid-input-group">
            <input 
              type="number" 
              [(ngModel)]="bidAmount"
              placeholder="Enter bid amount"
              class="input"
              [disabled]="isBidding"
            />
            <span class="currency">ETH</span>
          </div>

          <button 
            (click)="placeBid()" 
            [disabled]="isBidding || !bidAmount"
            class="btn btn-primary"
          >
            {{ isBidding ? 'Placing Bid...' : 'Place Private Bid' }}
          </button>
        </div>
      </div>

      <div *ngIf="bids.length > 0" class="bids-card">
        <h3>📋 Your Bids</h3>
        <div class="bids-list">
          <div *ngFor="let bid of bids" class="bid-item" [class.confirmed]="bid.status === 'confirmed'">
            <div class="bid-header">
              <span class="bid-id">Bid #{{ bid.id }}</span>
              <span class="bid-time">{{ getTimeSince(bid.timestamp) }}</span>
            </div>
            <div class="bid-details">
              <span class="bid-amount">Amount: {{ bid.amount }}</span>
              <span class="bid-status" [class.pending]="bid.status === 'pending'">
                {{ bid.status === 'confirmed' ? '✓ Confirmed' : '⏳ Pending' }}
              </span>
            </div>
            <div *ngIf="bid.encryptedHandle && bid.status === 'confirmed'" class="bid-actions">
              <button 
                (click)="revealBid(bid)" 
                [disabled]="bid.isDecrypting || bid.decryptedAmount !== undefined"
                class="btn btn-reveal"
              >
                {{ bid.isDecrypting ? 'Decrypting...' : bid.decryptedAmount ? '✓ Revealed' : '🔓 Reveal Bid' }}
              </button>
              <div *ngIf="bid.decryptedAmount !== undefined" class="revealed-amount">
                💰 {{ bid.decryptedAmount.toString() }} ETH
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="info-card">
        <h3>ℹ️ How Blind Auctions Work</h3>
        <ul>
          <li>All bids are encrypted using FHE</li>
          <li>Bidders cannot see each other's amounts</li>
          <li>Winner is determined without revealing losing bids</li>
          <li>Complete privacy for all participants</li>
        </ul>
      </div>
    </div>
  </ng-container>
</div>

// examples/solid-poll/src/App.tsx
import { createSignal, Show, For } from 'solid-js'
import { FHEVMProvider, useFHEVM } from '@mixaspro/solid'
import { createWallet } from '@mixaspro/solid'
import { createEncrypt } from '@mixaspro/solid'
import { createDecrypt } from '@mixaspro/solid'

const POLL_ABI = [
  {
    inputs: [{ name: 'encryptedChoice', type: 'bytes' }],
    name: 'vote',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getResults',
    outputs: [{ name: '', type: 'euint32[]' }],
    stateMutability: 'view',
    type: 'function',
  },
]

const CONTRACT_ADDRESS = '0x5FbDB2315678afecb367f032d93F642f64180aa3'

const pollOptions = [
  { id: 0, title: '🍕 Pizza', description: 'Classic choice' },
  { id: 1, title: '🍔 Burger', description: 'American favorite' },
  { id: 2, title: '🍜 Ramen', description: 'Asian delight' },
  { id: 3, title: '🌮 Tacos', description: 'Mexican taste' },
]

function PollContent() {
  const fhevm = useFHEVM()
  const wallet = createWallet()
  const encrypt = createEncrypt()
  const decrypt = createDecrypt()
  
  const [selectedOption, setSelectedOption] = createSignal<number | null>(null)
  const [isVoting, setIsVoting] = createSignal(false)
  const [hasVoted, setHasVoted] = createSignal(false)
  const [txHash, setTxHash] = createSignal('')
  const [encryptedHandle, setEncryptedHandle] = createSignal<string | null>(null)
  const [decryptedVote, setDecryptedVote] = createSignal<bigint | null>(null)
  const [connectedWallet, setConnectedWallet] = createSignal<any>(null)

  const handleConnect = async () => {
    try {
      if (!(window as any).ethereum) {
        alert('MetaMask not found! Please install MetaMask.')
        return
      }
      
      const client = fhevm.client()
      if (!client) {
        alert('FHEVM client not initialized')
        return
      }
      
      console.log('Connecting wallet...')
      await client.connectWallet((window as any).ethereum)
      const walletInfo = client.getWallet()
      console.log('Wallet connected:', walletInfo)
      setConnectedWallet(walletInfo)
    } catch (error) {
      console.error('Failed to connect:', error)
      alert('Failed to connect wallet: ' + (error instanceof Error ? error.message : 'Unknown error'))
    }
  }

  const handleVote = async () => {
    const choice = selectedOption()
    if (choice === null) {
      alert('Please select an option')
      return
    }

    const client = fhevm.client()
    if (!client) {
      alert('FHEVM client not available')
      return
    }

    setIsVoting(true)
    try {
      const encrypted = await client.encrypt(choice, 'euint32')
      
      // Store handle for decryption
      if (encrypted && encrypted.handle) {
        setEncryptedHandle(encrypted.handle)
      }
      
      // In real app, would call contract
      setTxHash('0x1234567890abcdef')
      setHasVoted(true)
      alert('Vote submitted successfully!')
    } catch (error) {
      console.error('Vote failed:', error)
      alert(`Failed to vote: ${error instanceof Error ? error.message : 'Unknown error'}`)
    } finally {
      setIsVoting(false)
    }
  }

  const handleDecryptVote = async () => {
    const handle = encryptedHandle()
    if (!handle) {
      alert('No encrypted vote to decrypt')
      return
    }

    const client = fhevm.client()
    if (!client) {
      alert('FHEVM client not available')
      return
    }

    try {
      const instance = client.getInstance()
      if (!instance) {
        throw new Error('FHEVM instance not available')
      }
      
      const results = await instance.publicDecrypt([handle])
      const handles = Object.keys(results)
      if (handles.length > 0) {
        setDecryptedVote(results[handles[0]] as bigint)
      }
    } catch (error) {
      console.error('Decryption failed:', error)
      alert(`Decryption failed: ${error instanceof Error ? error.message : 'Unknown error'}`)
    }
  }

  const shortAddress = (addr: string) => {
    return `${addr.slice(0, 6)}...${addr.slice(-4)}`
  }

  return (
    <div class="container">
      <header>
        <h1>📊 Private Poll</h1>
        <p class="subtitle">Solid.js + FHEVM SDK</p>
        <Show when={fhevm.network()}>
          <p class="network">Network: {fhevm.network()?.name || 'Unknown'}</p>
        </Show>
      </header>

      <Show when={!fhevm.isInitialized()}>
        <div class="loading">Initializing FHEVM...</div>
      </Show>

      <Show when={fhevm.isInitialized()}>
        <Show
          when={connectedWallet()?.address}
          fallback={
            <div class="wallet-section">
              <button 
                onClick={handleConnect}
                disabled={wallet.isConnecting()}
                class="btn btn-primary"
              >
                {wallet.isConnecting() ? 'Connecting...' : 'Connect Wallet'}
              </button>
            </div>
          }
        >
          <div class="main-content">
            <div class="wallet-info">
              <p><strong>Connected:</strong> {shortAddress(connectedWallet()!.address)}</p>
              <button onClick={() => setConnectedWallet(null)} class="btn btn-secondary">
                Disconnect
              </button>
            </div>

            <Show when={!hasVoted()}>
              <div class="card">
                <h2>🗳️ What's your favorite food?</h2>
                <p class="poll-description">
                  Your vote is encrypted and completely private. No one can see what you voted for!
                </p>

                <div class="options">
                  <For each={pollOptions}>
                    {(option) => (
                      <div
                        class={`option ${selectedOption() === option.id ? 'selected' : ''}`}
                        onClick={() => setSelectedOption(option.id)}
                      >
                        <div class="option-title">{option.title}</div>
                        <div class="option-description">{option.description}</div>
                      </div>
                    )}
                  </For>
                </div>

                <button
                  onClick={handleVote}
                  disabled={isVoting() || selectedOption() === null}
                  class="btn btn-primary"
                >
                  {isVoting() ? 'Submitting Vote...' : 'Submit Private Vote'}
                </button>
              </div>
            </Show>

            <Show when={hasVoted()}>
              <div class="card success-card">
                <h2>✅ Vote Submitted!</h2>
                <p>Your vote has been recorded privately on the blockchain.</p>
                <p class="tx-hash">TX: {shortAddress(txHash())}</p>
                <p class="privacy-note">
                  🔒 Your choice is encrypted and cannot be viewed by anyone, 
                  including the contract owner.
                </p>
                
                <Show when={encryptedHandle()}>
                  <div class="decrypt-section">
                    <h3>Verify Your Vote</h3>
                    <p>Decrypt to verify your encrypted vote value</p>
                    <button
                      onClick={handleDecryptVote}
                      disabled={decrypt.isDecrypting()}
                      class="btn btn-decrypt"
                    >
                      {decrypt.isDecrypting() ? 'Decrypting...' : '🔓 Decrypt My Vote'}
                    </button>
                    
                    <Show when={decrypt.error()}>
                      <div class="error-message">
                        ❌ {decrypt.error()!.message}
                      </div>
                    </Show>
                    
                    <Show when={decryptedVote() !== null}>
                      <div class="decrypted-result">
                        <h4>Decrypted Vote:</h4>
                        <p class="vote-choice">
                          {pollOptions[Number(decryptedVote())]?.title || 'Unknown'}
                        </p>
                        <p class="vote-id">Value: {decryptedVote()!.toString()}</p>
                      </div>
                    </Show>
                  </div>
                </Show>
              </div>
            </Show>

            <div class="card info-card">
              <h3>ℹ️ How it works</h3>
              <ul>
                <li>Your vote is encrypted using Fully Homomorphic Encryption (FHE)</li>
                <li>Only encrypted data is stored on-chain</li>
                <li>Results can be computed without revealing individual votes</li>
                <li>Complete privacy guaranteed by cryptography</li>
              </ul>
            </div>
          </div>
        </Show>
      </Show>
    </div>
  )
}

export default function App() {
  return (
    <FHEVMProvider
      config={{
        chainId: 11155111,
        rpcUrl: 'https://eth-sepolia.g.alchemy.com/v2/tdHjNLQj6qDZOj8XlibqQEVxvKh_5Tqw',
        wasmPath: '/solid-poll/wasm/'
      }}
      autoInit={true}
    >
      <PollContent />
    </FHEVMProvider>
  )
}
